# Builder CI pipeline
stages:
  - build
  - validate
  - publish

build:
  stage: build
  script:
    - mkdir -p out
    - echo "Building executable..."
    - echo "Hello, world!" > out/my_executable.bin
    - sha256sum out/my_executable.bin | awk '{print $1}' > out/my_executable.sha256
    - echo "Executable built successfully."
  artifacts:
    paths:
      - out/**
    when: always
    expire_in: 1 day

validate:
  stage: validate
  needs:
    - job: build
      artifacts: true
  script:
    - echo "Validating executable..."
    - test -f out/my_executable.bin || (echo "Error: Executable not found!" && exit 1)
    - test -f out/my_executable.sha256 || (echo "Error: SHA256 checksum not found!" && exit 1)
    - echo "Validation passed."
  artifacts:
    paths:
      - out/**
    when: always
    expire_in: 1 day

publish:
  stage: publish
  needs:
    - job: validate
      artifacts: true
  script:
    - echo "Publishing metadata..."
    - jq -n \
        --arg service_name "Builder" \
        --arg repository_url "$CI_PROJECT_URL" \
        --arg commit_sha "$CI_COMMIT_SHA" \
        --arg pipeline_url "$CI_PIPELINE_URL" \
        --arg run_id "$RUN_ID" \
        --arg built_file "my_executable.bin" \
        '{
          service_name: $service_name,
          repository_url: $repository_url,
          commit_sha: $commit_sha,
          pipeline_url: $pipeline_url,
          run_id: $run_id,
          built_file: $built_file
        }' > out/service_meta.json
    - echo "Metadata published successfully."
  artifacts:
    paths:
      - out/**
    when: always
    expire_in: 1 day
