# gitlab-ci-dag.yml
#
# Orchestrator CI pipeline (reference implementation)
#
# This pipeline defines the workflow DAG and serves as the single marshaler and publisher.
# It triggers service overlay pipelines, resolves their downstream artifact-producing jobs,
# downloads artifacts via the GitLab API, bundles outputs, applies gate logic, and publishes
# a final run bundle to the bus (Generic Package Registry).
#
# Required variables:
# - OWO_BUS_PROJECT_ID (numeric GitLab project id that hosts the bus package registry)
# - OWO_BUS_PACKAGE (generic package name, e.g. "owo-runs")
#
# Optional services (metrics/sandbox/scanner) are controlled by *_REF:
# - If OWO_<SERVICE>_REF is empty, that service is skipped.
# - VT_TIMEOUT_SECONDS (optional) passed to the scanner overlay
# - VT_POLL_INTERVAL_SECONDS (optional) passed to the scanner overlay
# - Bundle is always encrypted with RUN_ID (lightweight friction; not a security control)
#
# Generated variables:
# - RUN_ID (UUID) generated at kickoff and propagated to services
#
# Standardized overlay contract:
# - Downstream pipelines MUST produce artifacts from a job named exactly "run"
#   containing at least: out/service_meta.json
#
# Notes:
# - This pipeline uses the GitLab API with CI_JOB_TOKEN for resolving downstream pipelines and downloading artifacts.
# - Ensure the runner image includes: curl, jq, 7z, unzip, uuidgen.

include:
  - local: ci/templates.yml

stages:
  - kickoff
  - trigger
  - resolve
  - collect
  - bundle
  - gate
  - publish

default:
  image: alpine:3.23
  before_script:
    - apk add --no-cache bash curl jq unzip p7zip util-linux coreutils
  variables:
    GIT_STRATEGY: none

variables:
  # Service projects (override in CI/CD variables if yours differ)
  OWO_BUILDER_PROJECT: "owo/builder-hello"
  OWO_METRICS_PROJECT: "owo/metrics-basic"
  OWO_SANDBOX_PROJECT: "owo/sandbox-exec"
  OWO_SCANNER_PROJECT: "owo/scanner-virustotal"

  # Optional services default off (HTML/URL sets these per run)
  OWO_METRICS_REF: ""
  OWO_SANDBOX_REF: ""
  OWO_SCANNER_REF: ""

  # Standardized artifacts job name in ALL downstream pipelines
  OWO_ARTIFACT_JOB_NAME: "^run$"

kickoff:
  stage: kickoff
  script: |-
    set -euo pipefail

    test -n "${OWO_BUS_PROJECT_ID:-}" || (echo "Error: OWO_BUS_PROJECT_ID is required (numeric bus project id)." >&2; exit 1)
    echo "$OWO_BUS_PROJECT_ID" | grep -Eq '^[0-9]+$' || (echo "Error: OWO_BUS_PROJECT_ID must be numeric." >&2; exit 1)
    test -n "${OWO_BUS_PACKAGE:-}" || (echo "Error: OWO_BUS_PACKAGE is required (generic package name)." >&2; exit 1)

    # Allow caller to supply RUN_ID; otherwise generate it.
    if [ -z "${RUN_ID:-}" ]; then
      RUN_ID="$(uuidgen)"
    fi

    # Normalize refs: builder always defaults to main, others are optional.
    : "${OWO_BUILDER_REF:=main}"
    : "${OWO_METRICS_REF:=}"
    : "${OWO_SANDBOX_REF:=}"
    : "${OWO_SCANNER_REF:=}"

    {
      echo "RUN_ID=$RUN_ID";
      echo "OWO_BUS_PROJECT_ID=$OWO_BUS_PROJECT_ID";
      echo "OWO_BUS_PACKAGE=$OWO_BUS_PACKAGE";

      echo "OWO_BUILDER_REF=$OWO_BUILDER_REF";
      echo "OWO_METRICS_REF=$OWO_METRICS_REF";
      echo "OWO_SANDBOX_REF=$OWO_SANDBOX_REF";
      echo "OWO_SCANNER_REF=$OWO_SCANNER_REF";
    } | tee run.env
  artifacts:
    reports:
      dotenv: run.env
    expire_in: 1 day

# -----------------------------------------------------------------------------
# TRIGGER STAGE
# -----------------------------------------------------------------------------

trigger_builder:
  stage: trigger
  needs:
    - job: kickoff
      artifacts: true
  trigger:
    project: "$OWO_BUILDER_PROJECT"
    branch: "$OWO_BUILDER_REF"
    strategy: depend
  variables:
    RUN_ID: "$RUN_ID"
    OWO_BUS_PROJECT_ID: "$OWO_BUS_PROJECT_ID"
    OWO_BUS_PACKAGE: "$OWO_BUS_PACKAGE"
  allow_failure: false

# Builder resolve MUST be in stage=trigger so optional downstream triggers can legally needs it.
resolve_builder:
  extends: .resolve_downstream_template
  stage: trigger
  needs:
    - job: kickoff
      artifacts: true
    - job: trigger_builder
  variables:
    TRIGGER_JOB_NAME: "trigger_builder"
    PREFIX: "BUILDER"

trigger_metrics:
  stage: trigger
  needs:
    - job: kickoff
      artifacts: true
    - job: resolve_builder
      artifacts: true
  rules:
    - if: '$OWO_METRICS_REF'
      when: on_success
    - when: never
  trigger:
    project: "$OWO_METRICS_PROJECT"
    branch: "$OWO_METRICS_REF"
    strategy: depend
  variables:
    RUN_ID: "$RUN_ID"
    BUILDER_PROJECT_ID: "$BUILDER_PROJECT_ID"
    BUILDER_JOB_ID: "$BUILDER_JOB_ID"

trigger_sandbox:
  stage: trigger
  needs:
    - job: kickoff
      artifacts: true
    - job: resolve_builder
      artifacts: true
  rules:
    - if: '$OWO_SANDBOX_REF'
      when: on_success
    - when: never
  trigger:
    project: "$OWO_SANDBOX_PROJECT"
    branch: "$OWO_SANDBOX_REF"
    strategy: depend
  variables:
    RUN_ID: "$RUN_ID"
    BUILDER_PROJECT_ID: "$BUILDER_PROJECT_ID"
    BUILDER_JOB_ID: "$BUILDER_JOB_ID"

trigger_scanner:
  stage: trigger
  needs:
    - job: kickoff
      artifacts: true
    - job: resolve_builder
      artifacts: true
  rules:
    - if: '$OWO_SCANNER_REF'
      when: on_success
    - when: never
  trigger:
    project: "$OWO_SCANNER_PROJECT"
    branch: "$OWO_SCANNER_REF"
    strategy: depend
  variables:
    RUN_ID: "$RUN_ID"
    BUILDER_PROJECT_ID: "$BUILDER_PROJECT_ID"
    BUILDER_JOB_ID: "$BUILDER_JOB_ID"
    VT_TIMEOUT_SECONDS: "$VT_TIMEOUT_SECONDS"
    VT_POLL_INTERVAL_SECONDS: "$VT_POLL_INTERVAL_SECONDS"

# -----------------------------------------------------------------------------
# RESOLVE STAGE (optional services)
# -----------------------------------------------------------------------------

resolve_metrics:
  extends: .resolve_downstream_template
  needs:
    - job: kickoff
      artifacts: true
    - job: trigger_metrics
      optional: true
  rules:
    - if: '$OWO_METRICS_REF'
      when: on_success
    - when: never
  variables:
    TRIGGER_JOB_NAME: "trigger_metrics"
    PREFIX: "METRICS"

resolve_sandbox:
  extends: .resolve_downstream_template
  needs:
    - job: kickoff
      artifacts: true
    - job: trigger_sandbox
      optional: true
  rules:
    - if: '$OWO_SANDBOX_REF'
      when: on_success
    - when: never
  variables:
    TRIGGER_JOB_NAME: "trigger_sandbox"
    PREFIX: "SANDBOX"

resolve_scanner:
  extends: .resolve_downstream_template
  needs:
    - job: kickoff
      artifacts: true
    - job: trigger_scanner
      optional: true
  rules:
    - if: '$OWO_SCANNER_REF'
      when: on_success
    - when: never
  variables:
    TRIGGER_JOB_NAME: "trigger_scanner"
    PREFIX: "SCANNER"

# -----------------------------------------------------------------------------
# COLLECT STAGE
# -----------------------------------------------------------------------------

collect_builder:
  extends: .collect_template
  needs:
    - job: kickoff
      artifacts: true
    - job: resolve_builder
      artifacts: true
  variables:
    SERVICE: "builder"
    PROJECT_ID: "$BUILDER_PROJECT_ID"
    JOB_ID: "$BUILDER_JOB_ID"

collect_metrics:
  extends: .collect_template
  needs:
    - job: kickoff
      artifacts: true
    - job: resolve_metrics
      artifacts: true
      optional: true
  rules:
    - if: '$OWO_METRICS_REF'
      when: on_success
    - when: never
  variables:
    SERVICE: "metrics"
    PROJECT_ID: "$METRICS_PROJECT_ID"
    JOB_ID: "$METRICS_JOB_ID"

collect_sandbox:
  extends: .collect_template
  needs:
    - job: kickoff
      artifacts: true
    - job: resolve_sandbox
      artifacts: true
      optional: true
  rules:
    - if: '$OWO_SANDBOX_REF'
      when: on_success
    - when: never
  variables:
    SERVICE: "sandbox"
    PROJECT_ID: "$SANDBOX_PROJECT_ID"
    JOB_ID: "$SANDBOX_JOB_ID"

collect_scanner:
  extends: .collect_template
  needs:
    - job: kickoff
      artifacts: true
    - job: resolve_scanner
      artifacts: true
      optional: true
  rules:
    - if: '$OWO_SCANNER_REF'
      when: on_success
    - when: never
  variables:
    SERVICE: "scanner"
    PROJECT_ID: "$SCANNER_PROJECT_ID"
    JOB_ID: "$SCANNER_JOB_ID"

# -----------------------------------------------------------------------------
# BUNDLE / GATE / PUBLISH
# -----------------------------------------------------------------------------

bundle:
  stage: bundle
  needs:
    - job: kickoff
      artifacts: true
    - job: collect_builder
      artifacts: true
    - job: collect_metrics
      artifacts: true
      optional: true
    - job: collect_sandbox
      artifacts: true
      optional: true
    - job: collect_scanner
      artifacts: true
      optional: true
  script: |-
    set -euo pipefail

    mkdir -p final

    jq -n --arg run_id "$RUN_ID" '{run_id:$run_id}' | tee manifest.json

    7z a -t7z -p"$RUN_ID" -mhe=on "final/run-${RUN_ID}.7z" out/ manifest.json
  artifacts:
    paths:
      - final/run-*.7z
      - manifest.json
    expire_in: 7 days

gate:
  stage: gate
  needs:
    - job: bundle
      artifacts: true
    - job: collect_sandbox
      artifacts: true
      optional: true
  script: |-
    set -euo pipefail

    # Minimal gate: builder must exist.
    test -f out/builder/service_meta.json

    # Optional gate behavior: if sandbox ran, require sandbox metadata.
    if [ -n "${OWO_METRICS_REF:-}" ]; then
      test -f out/metrics/service_meta.json
    fi
    if [ -n "${OWO_SCANNER_REF:-}" ]; then
      test -f out/scanner/service_meta.json
    fi
    if [ -n "${OWO_SANDBOX_REF:-}" ]; then
      test -f out/sandbox/service_meta.json
    fi

publish_success:
  extends: .publish_to_bus_template
  when: on_success
  variables:
    BUS_SUFFIX: ""

publish_failed:
  extends: .publish_to_bus_template
  when: on_failure
  variables:
    BUS_SUFFIX: "-failed"
